type Product {
  productId: ID!
  title: String
  url: String
  category: String
  lowPrice: Float
}

type Query {
  getProduct(productId: ID!): Product
}

type Mutation {
  putProduct(productId: String!, title: String, url: String, category: String, lowPrice: Float): Product
}

schema {
  query: Query
  mutation: Mutation
}
